package XuanJi.core.plugin.storage;

import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * 插件结构化存储的 DDL 生成与迁移（复用框架既有的
 * {@code CREATE TABLE IF NOT EXISTS} + {@code ALTER ... ADD COLUMN IF NOT EXISTS} 风格）。
 *
 * <p>所有标识符（物理表名/列名/索引名）均已在 {@link PluginEntityScanner} 阶段过白名单，
 * 此处直接拼入 DDL；值一律由调用方参数化，本类只负责结构。
 *
 * <h3>安全约束</h3>
 * <ul>
 *   <li>建表幂等：{@code CREATE TABLE IF NOT EXISTS}。</li>
 *   <li>迁移只增不删：仅 {@code ADD COLUMN IF NOT EXISTS}，<b>绝不 DROP</b>。</li>
 *   <li>行数配额：{@code xuanji_plugin_data_meta} 计数表，单表上限 {@link #MAX_ROWS}。</li>
 * </ul>
 */
@Slf4j(topic = "xuanji.plugin.storage")
@Component
public class PluginSchemaGenerator {

    /** 单插件单表行数配额。 */
    public static final long MAX_ROWS = 100_000L;

    public static final String REGISTRY_TABLE = "xuanji_plugin_entity_schema";
    public static final String META_TABLE = "xuanji_plugin_data_meta";

    /** 框架托管自增列（无 @PluginAutoId 时使用）。 */
    private static final String ROW_ID = "row_id";

    /** 创建框架登记/配额表（幂等）。 */
    public void createFrameworkTables(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE IF NOT EXISTS " + REGISTRY_TABLE + " ("
                + "plugin_id VARCHAR(128) NOT NULL, "
                + "entity VARCHAR(255) NOT NULL, "
                + "table_name VARCHAR(128) NOT NULL, "
                + "version INT NOT NULL, "
                + "columns_hash VARCHAR(32) NOT NULL, "
                + "PRIMARY KEY (plugin_id, table_name))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS " + META_TABLE + " ("
                + "plugin_id VARCHAR(128) NOT NULL, "
                + "table_name VARCHAR(128) NOT NULL, "
                + "row_count BIGINT NOT NULL DEFAULT 0, "
                + "PRIMARY KEY (plugin_id, table_name))");
    }

    /** 建表（幂等）+ 登记 + 配额行初始化。 */
    public void createTable(JdbcTemplate jdbc, EntityMetadata meta) {
        StringBuilder sb = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                .append(meta.physicalTable).append(" (");
        List<String> defs = new ArrayList<>();
        if (meta.autoIdColumn != null) {
            defs.add(meta.autoIdColumn + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        } else {
            defs.add(ROW_ID + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        }
        for (EntityMetadata.ColumnMeta c : meta.columns) {
            StringBuilder cd = new StringBuilder()
                    .append(c.columnName).append(' ').append(c.sqlType);
            if (!c.nullable) cd.append(" NOT NULL");
            if (c.unique) cd.append(" UNIQUE");
            defs.add(cd.toString());
        }
        // 业务主键 → 复合唯一约束（无论是否有自增列，都需唯一以支撑 MERGE KEY upsert 的精确匹配）
        if (!meta.primaryKeyColumns.isEmpty()) {
            defs.add("UNIQUE (" + String.join(", ", meta.primaryKeyColumns) + ")");
        }
        sb.append(String.join(", ", defs)).append(')');
        jdbc.execute(sb.toString());

        // 二级索引（<=4，已在扫描期限制）
        for (EntityMetadata.ColumnMeta c : meta.columns) {
            if (c.index) {
                String idx = "idx_" + meta.logicalTable + "_" + c.columnName;
                jdbc.execute("CREATE INDEX IF NOT EXISTS " + idx
                        + " ON " + meta.physicalTable + " (" + c.columnName + ")");
            }
        }

        registerEntity(jdbc, meta);
        ensureMetaRow(jdbc, meta.pluginId, meta.physicalTable);
        log.info("[Storage] 已建表 {} (实体 {}, 字段数 {})", meta.physicalTable,
                meta.entityClass.getSimpleName(), meta.columns.size());
    }

    /** 迁移：仅新增列（ADD COLUMN IF NOT EXISTS），更新登记指纹。 */
    public void migrate(JdbcTemplate jdbc, EntityMetadata meta) {
        for (EntityMetadata.ColumnMeta c : meta.columns) {
            // 迁移期新增列强制可空，避免既有行无默认值导致 ALTER 失败
            jdbc.execute("ALTER TABLE " + meta.physicalTable
                    + " ADD COLUMN IF NOT EXISTS " + c.columnName + " " + c.sqlType);
        }
        registerEntity(jdbc, meta);
        log.info("[Storage] 已迁移表 {} (实体 {})", meta.physicalTable, meta.entityClass.getSimpleName());
    }

    /** 登记/更新实体结构指纹。 */
    public void registerEntity(JdbcTemplate jdbc, EntityMetadata meta) {
        jdbc.update("MERGE INTO " + REGISTRY_TABLE
                        + " (plugin_id, entity, table_name, version, columns_hash) "
                        + "KEY(plugin_id, table_name) VALUES (?, ?, ?, ?, ?)",
                meta.pluginId, meta.entityClass.getName(), meta.physicalTable, meta.version, meta.columnsHash);
    }

    /** 读取已登记的结构指纹（用于判断是否需要迁移）。 */
    public String registeredHash(JdbcTemplate jdbc, String pluginId, String physicalTable) {
        try {
            return jdbc.queryForObject(
                    "SELECT columns_hash FROM " + REGISTRY_TABLE
                            + " WHERE plugin_id=? AND table_name=?",
                    String.class, pluginId, physicalTable);
        } catch (Exception e) {
            return null;
        }
    }

    private void ensureMetaRow(JdbcTemplate jdbc, String pluginId, String table) {
        jdbc.update("MERGE INTO " + META_TABLE + " (plugin_id, table_name, row_count) "
                + "KEY(plugin_id, table_name) VALUES (?, ?, 0)", pluginId, table);
    }

    /** 当前行数（来自配额计数表，避免全表 COUNT）。 */
    public long rowCount(JdbcTemplate jdbc, String pluginId, String table) {
        try {
            Long n = jdbc.queryForObject(
                    "SELECT row_count FROM " + META_TABLE + " WHERE plugin_id=? AND table_name=?",
                    Long.class, pluginId, table);
            return n == null ? 0L : n;
        } catch (Exception e) {
            return 0L;
        }
    }

    /** 是否仍在配额内（拟新增 add 行后不超过上限）。 */
    public boolean withinQuota(JdbcTemplate jdbc, String pluginId, String table, long add) {
        return rowCount(jdbc, pluginId, table) + add <= MAX_ROWS;
    }

    /** 调整配额计数（delta 可正可负，下限 0）。 */
    public void adjustRows(JdbcTemplate jdbc, String pluginId, String table, long delta) {
        Long cur = jdbc.queryForObject(
                "SELECT row_count FROM " + META_TABLE + " WHERE plugin_id=? AND table_name=?",
                Long.class, pluginId, table);
        long next = Math.max(0, (cur == null ? 0 : cur) + delta);
        if (cur == null) {
            jdbc.update("INSERT INTO " + META_TABLE + " (plugin_id, table_name, row_count) VALUES (?, ?, ?)",
                    pluginId, table, next);
        } else {
            jdbc.update("UPDATE " + META_TABLE + " SET row_count=? WHERE plugin_id=? AND table_name=?",
                    next, pluginId, table);
        }
    }
}
